### ISSUE TITLE
addrspace/multiple HEAP support?

### ISSUE THREAD

**Issue by ejgallego** [emscripten-core/emscripten-fastcomp#118]
Hello,

currently, the memory space of code generated by emscripten seems to be limited to a single HEAP, which is a JS TypedArray.

As it has been discussed several times, this is a bit inconvenient for some interactions with JS API that provide TypedArray buffers allocated by them, in particular webAudio and I believe WebCanvas do this, and avoiding a copy may be difficult given that these buffers come from the OS stack.

Supporting multiple HEAPs could alleviate this issue (even if care has to be taken in order for the asm.js optimizations to remain in place).

Would it make sense for emscripten to support several heaps? A simple way to implement this feature could be to use LLVM's `addrspace` pointer attribute to mark the desired heap, as in this example:

``` llvm
; Example of address spaces for JS/EMSCRIPTEN
; Run with $ llvm-as addr-example.ll -o - -f | opt -mem2reg | llc
target triple = "asmjs-unknown-emscripten"

; Values residing in two different address spaces, the idea is that we
; can map an address space to a particular HEAP
@V0 =              global i32 0
@V1 = addrspace(1) global i32 0

define i32 @test_add () {
   %r0 = load i32, i32 addrspace(0)* @V0
   %r1 = load i32, i32 addrspace(1)* @V1
   %rr = add i32 %r0, %r1
   ret i32 %rr
}
```

which currently generates:

``` js
function _test_add() {
 var $r0 = 0, $r1 = 0, $rr = 0, label = 0, sp = 0;
 sp = STACKTOP;
 $r0 = HEAP32[2]|0;
 $r1 = HEAP32[4]|0;
 $rr = (($r0) + ($r1))|0;
 return ($rr|0);
}
```

but after multiple heap support should output something like:

``` js
function _test_add() {
 var $r0 = 0, $r1 = 0, $rr = 0, label = 0, sp = 0;
 sp = STACKTOP;
 $r0 = HEAP1_32[2]|0;
 $r1 = HEAP32[2]|0;
 $rr = (($r0) + ($r1))|0;
 return ($rr|0);
}
```

Do you think it would make sense then?

I'm far from knowledgeable in LLVM or EMSCRIPTEN, but after a brief look to the code it seems to me that a possible way to implement this feature would be to refactor `getLoad` and `getStore` in JSBackend.c to query the `addrspace` attribute of the pointer.

Maybe even moving code to a `Heap` class could work, I dunno.

Regards,
Emilio

**Comment by kripken** [comment]
We can't do this in asm.js, but we can do it in non-asm.js code. It won't be as fast, but the memory flexibility can be useful.

In fact, there is an experiment doing this right now, see the `split_memory` branch in emscripten. It splits the heap into slices, and each one is backed up by a separate typed array. Right now, malloc is in charge of the slices, creating more as needed, etc., but we could add an option to fill a slice with an existing buffer. That is, given an ArrayBuffer, we could put it in the list of chunks, and it would be addressed normally at that offset.

But again, if you want this for speed, I doubt it will help. A copy into the emscripten heap is going to be faster than running in non-asm.js mode, especially non-asm.js with a split heap, I see 2-3x slowdowns on average. (But, the memory flexibility is useful for other things.)

**Comment by ejgallego** [comment]
Thank you for the reply @kripken , I'll have a look to the split_memory branch.

I assumed that asm.js mode would be disabled in the presence of several heaps if them are not set up with care; do you think this is a fundamental limitation? 

In my uninformed and very limited understanding of both asm.js and emscripten, I thought that internal indexing throu a base pointer would be feasible to implement by the browsers (if they don't already do so).

Thanks, Emilio
p.d: So what happens if after running some asm.js code, HEAP is reallocated from JS.

**Comment by kripken** [comment]
asm.js has a spec. Anything with a more flexible heap will simply not validate.

Currently browsers are focused on WebAssembly, which takes the good parts of asm.js and standardizes them. A more flexible heap could be proposed there, and some ideas have been, but overall I think the same will remain there - the heap will be simple linear memory.

However, non-asm.js can be quite fast too. A 2-3x slowdown still means the code is pretty fast, around the speed of languages like Java and C#.
