### ISSUE TITLE
build emscripten-fastcomp from src failed

### ISSUE THREAD

**Issue by anddyhzw** [emscripten-core/emscripten-fastcomp#128]
Stack dump:
0.  Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.9.0 -emit-obj -disable-free -disable-llvm-verifier -main-file-name CGBlocks.cpp -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -relaxed-aliasing -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 241.9 -coverage-file /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/build/tools/clang/lib/CodeGen/Release/CGBlocks.o -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0 -dependency-file /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/build/tools/clang/lib/CodeGen/Release/CGBlocks.d.tmp -MP -MT /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/build/tools/clang/lib/CodeGen/Release/CGBlocks.o -MT /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/build/tools/clang/lib/CodeGen/Release/CGBlocks.d -D NDEBUG -D _GNU_SOURCE -D __STDC_CONSTANT_MACROS -D __STDC_FORMAT_MACROS -D __STDC_LIMIT_MACROS -I /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/build/include -I /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/build/tools/clang/lib/CodeGen -I /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/include -I /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/tools/clang/lib/CodeGen -I /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/tools/clang/lib/CodeGen/../../include -I /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/build/tools/clang/lib/CodeGen/../../include -stdlib=libc++ -O3 -Wcast-qual -Wno-long-long -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcovered-switch-default -Wmissing-field-initializers -Wno-comment -pedantic -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/build/tools/clang/lib/CodeGen -ferror-limit 19 -fmessage-length 80 -fvisibility-inlines-hidden -stack-protector 1 -mstackrealign -fblocks -fno-rtti -fobjc-runtime=macosx-10.9.0 -fencode-extended-block-signature -fno-common -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/build/tools/clang/lib/CodeGen/Release/CGBlocks.o -x c++ /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/tools/clang/lib/CodeGen/CGBlocks.cpp 
1.  <eof> parser at end of file
2.  Code generation
3.  Running pass 'Function Pass Manager' on module '/Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/tools/clang/lib/CodeGen/CGBlocks.cpp'.
4.  Running pass 'X86 DAG->DAG Instruction Selection' on function '@_ZN5clang7CodeGen15CodeGenFunction12EmitCallArgsINS_17FunctionProtoTypeEEEvRNS0_11CallArgListEPKT_N4llvm14iterator_rangeINS_4Stmt17ConstExprIteratorEEEPKNS_12FunctionDeclEj'
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 

---

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/j4/r69d7_d96n366ngn89lv53ww0000gn/T/CGBlocks-416eaf.cpp
clang: note: diagnostic msg: /var/folders/j4/r69d7_d96n366ngn89lv53ww0000gn/T/CGBlocks-416eaf.sh
clang: note: diagnostic msg: 

---

rm: /Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/build/tools/clang/lib/CodeGen/Release/CGBlocks.d.tmp: No such file or directory
make[4]: **\* [/Users/hezhiwu/Desktop/emscriptenSVN_incoming/myfastcomp/emscripten-fastcomp/build/tools/clang/lib/CodeGen/Release/CGBlocks.o] Error 1
make[3]: **\* [CodeGen/.makeall] Error 2
make[3]: **\* Waiting for unfinished jobs....

**Comment by kripken** [comment]
A segfault in clang? Very strange. Which clang are you using?

**Comment by juj** [comment]
I remember to having to upgrade OS X or Xcode (upgraded both, don't know which was the important bit) after we migrated from PNaCl LLVM 3.7 repo to upstream LLVM 3.8 repo, or I would get a internal crash in OS X -provided native Clang compiler. I can't remember what my old versions were, but on OS X 10.11.1 El Capitan and Xcode 7.1 (7B91b) with Apple LLVM version 7.0.0 (clang-700.1.76) the build succeeded without internal errors.

Which versions of OS X and Xcode was this on? I see the Apple LLVM is at 6.0.0, so try upgrading that?

**Comment by anddyhzw** [comment]
Oh,I'm sorry to response so late. Because my ssd of macbook pro has one problem which is reading s.m.a.r.t status failed that stop me from updating my OS X  to 10.11.1 EI Capitan. So Could you provide me another solution,thank you very much.

**Comment by juj** [comment]
Perhaps try pulling upstream latest Clang+LLVM from llvm.org, or latest GCC from trunk tag, or homebrew/macports or similar, and try using that to build instead?
