### ISSUE TITLE
How to integrate JSBackend with clang & llvm

### ISSUE THREAD

**Issue by ramki1979** [emscripten-core/emscripten-fastcomp#140]
I want to study JSBackend, if it produces JS source from llvm ir.
How to integrate and study[reference to any docs or something] JSBackend with llvm, clang without using Emscripten.

**Comment by kripken** [comment]
Overview here might help https://kripken.github.io/emscripten-site/docs/contributing/developers_guide.html but overall, not much docs except for comments in the source code (in lib/Target/JSBackend/).
