### ISSUE TITLE
LLVM_TARGETS_TO_BUILD JSBackend only?

### ISSUE THREAD

**Issue by jirutka** [emscripten-core/emscripten-fastcomp#174]
Is it really needed to build LLVM/Fastcomp with `X86` target (on x86 system) when it’s used only to generate JS code or WebAssembly? Will it work even when I build it with `-DLLVM_TARGETS_TO_BUILD="JSBackend"`?

**Comment by kripken** [comment]
We do use the native compiler for some things, like building the asm.js optimizer from C++ to native code. It's also useful for debugging, to compare builds. But if you don't need those two things, it might be fine to not build the x86 target, but not 100% sure.
