### ISSUE TITLE
Support splitting Phi and Select over arrays.

### ISSUE THREAD

**Issue by eddyb** [emscripten-core/emscripten-fastcomp#178]
[Currently missing](https://github.com/kripken/emscripten-fastcomp/blob/881bd352731d21c7117ad7e2ece347aacae83965/lib/Target/JSBackend/NaCl/ExpandStructRegs.cpp#L540-L550), with only `Store` and `Load` supporting arrays.
Results in "Unrecognized struct value", see https://github.com/rust-lang/rust/pull/40658#issuecomment-292768371.

**Comment by kripken** [comment]
Thanks, PR for this in #179.
