### ISSUE TITLE
Web Assembly Backend

### ISSUE THREAD

**Issue by MichaReiser** [emscripten-core/emscripten-fastcomp#180]
Hy
Would it be possible to add the experimental Web Assembly backend to the build used by the emsdk? This would drastically simplify experimenting with the new backend compared to building llvm and clang all from source.

Might this be an option?

Thanks,
Micha

**Comment by kripken** [comment]
cc @juj, this would be just setting the cmake flags to include the experimental wasm backend to be built, I think.
