### ISSUE TITLE
config.guess line endings

### ISSUE THREAD

**Issue by fungos** [emscripten-core/emscripten-fastcomp#188]
Trying to install incoming 64bits on Manajaro Linux I get:

```
emsdk-portable/clang/fastcomp/src/cmake/config.guess: line 6: $'\r': command not found
emsdk-portable/clang/fastcomp/src/cmake/config.guess: line 8: $'\r': command not found
emsdk-portable/clang/fastcomp/src/cmake/config.guess: line 28: $'\r': command not found
emsdk-portable/clang/fastcomp/src/cmake/config.guess: line 29: $'\r': command not found
emsdk-portable/clang/fastcomp/src/cmake/config.guess: line 40: $'\r': command not found
emsdk-portable/clang/fastcomp/src/cmake/config.guess: line 42: $'\r': command not found
emsdk-portable/clang/fastcomp/src/cmake/config.guess: line 54: $'\r': command not found
emsdk-portable/clang/fastcomp/src/cmake/config.guess: line 65: $'\r': command not found
emsdk-portable/clang/fastcomp/src/cmake/config.guess: line 68: $'\r': command not found
emsdk-portable/clang/fastcomp/src/cmake/config.guess: line 71: syntax error near unexpected token `$'in\r''
'emsdk-portable/clang/fastcomp/src/cmake/config.guess: line 71: `  case $1 in
CMake Error at cmake/modules/GetHostTriple.cmake:24 (message):
  Failed to execute
  emsdk-portable/clang/fastcomp/src/cmake/config.guess
Call Stack (most recent call first):
  cmake/config-ix.cmake:344 (get_host_triple)
  CMakeLists.txt:583 (include)
```

doing a dos2unix config.guess fixed the problem.

**Comment by juj** [comment]
What is the sequence of commands you ran to install?

Added some print statements to the Emscripten repository line endings utility script (https://github.com/kripken/emscripten/commit/a4adea411c76813982ed772673eca69ec2138f78), and running that on my Linux Mint 18 installation:

```bash
clb@x10dax ~/emsdk $ ./emsdk install --build=Release sdk-incoming-64bit binaryen-master-64bit
clb@x10dax ~/emsdk $ ./emsdk activate --build=Release sdk-incoming-64bit binaryen-master-64bit
clb@x10dax ~/emsdk $ source ./emsdk_env.sh
clb@x10dax ~/emsdk $ python $EMSCRIPTEN/tools/line_endings.py clang/fastcomp/src/cmake/config.guess
File 'config.guess' contains UNIX "\n" line endings.
```

Is it only that single file with DOS line endings, or are there others? In the git repository this file does seem to have UNIX line endings.

**Comment by fungos** [comment]
```
curl -O https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
tar -xzf emsdk-portable.tar.gz
source emsdk_portable/emsdk_env.sh
emsdk update
emsdk install sdk-incoming-64bit
```

Just that file, then I fixed it  and everything finished.

**Comment by HarrySarson** [comment]
I also had this error building fastcomp from source as described by http://kripken.github.io/emscripten-site/docs/building_from_source/building_fastcomp_manually_from_source.html#building-fastcomp-from-source.

I am building on bash on windows and using dos2unix fixed the error.

**Comment by juj** [comment]
New Emsdk 1.37.13 was pushed live today, can you try if that resolves the issue? In my copy on Linux Mint 18 and macOS Sierra I get only \n line endings.

However @HarrySarson 's comment sounds like expected, on Windows if doing git clone on Windows terminal, it will produce DOS line endings unless git config has explicitly been instructed otherwise. MSYS, bash and Cygwin on Windows are a bit untrodden land for Emscripten on Windows, native command prompt is preferred (for setting up SDK at least)
