### ISSUE TITLE
Building on Solaris 11 (gcc version 4.8.2)

### ISSUE THREAD

**Issue by osen** [emscripten-core/emscripten-fastcomp#192]
Hello,

After encountering an issue with building using an obsolete MinGW, I tried a latest build of fastcomp on my Solaris 11 box to make sure it still works (The latest GCC compiler I can get from the official repo is version 4.8.2).

(I attempted to build from the latest opencsw compiler (5.2.0) but I got nowhere, the build system couldn't find pthread.h so failed)

So with 4.8.2, the build is generally straight forward and only fails due to one issue (occurs twice in the build). Basically either std::to_string (a C++ 11 feature) does not exist in the Solaris GCC 4.8.2 build or the compiler is not being passed the correct flag (-std=c++11). Unfortunately I cannot quite track down where this would be done in the masses of CMake scripts, perhaps someone with more familiarity of it can check?

I have uploaded to pastebin a terrible, terrible interim solution that I used to just make sure that the build could run to completion after these to_string issues are handled. It also shows the exact modules of the project need to be patched to fix the issue: https://pastebin.com/gJXEh0SN
After this fix, Emscripten and Fastcom work perfectly :)

Whilst I would not expect this patch to be applied, I was wondering if any of you guys had any suggestions on keeping Solaris support. I don't even know if it is one of your supported platforms to be honest.

**Comment by juj** [comment]
Searching the web suggests that MinGW did not have `std::to_string` until MinGW 4.8.0, see https://stackoverflow.com/questions/12975341/to-string-is-not-a-member-of-std-says-g-mingw and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52015, perhaps a similar bug existed for Solaris build of GCC, and got fixed only in a later version. Is GCC 4.8.2 the latest GCC that Solaris 11 ships with?

> Basically either std::to_string (a C++ 11 feature) does not exist in the Solaris GCC 4.8.2 build or the compiler is not being passed the correct flag (-std=c++11). Unfortunately I cannot quite track down where this would be done in the masses of CMake scripts, perhaps someone with more familiarity of it can check?

You can try with something like

```bash
git clone https://github.com/juj/emsdk.git
cd emsdk
./emsdk install --build=Release sdk-incoming-64bit
# After the build fails to the error:
cd clang/fastcomp/build_incoming_64
make VERBOSE=1
```

The last line attempts to incrementally continue the build from where it failed during the emsdk install step. The VERBOSE parameter should show the command line that is passed to compiling JSBackend.cpp.

**Comment by osen** [comment]
I am closing this issue because I tried the compile again in 2019 (with an updated build of Solaris 11) and there were no problems compiling.

Unfortunately I do not remember the exact compiler version but all was well.
