### ISSUE TITLE
Initializer Problem of LinkOnceAnyLinkage

### ISSUE THREAD

**Issue by tqchen** [emscripten-core/emscripten-fastcomp#217]
We are trying to use fastcomp backend for https://github.com/dmlc/tvm to compile deep learning to web. It has been great and we are quite excited about it.

However, we find a problem that might related to fastcomp backend. Specifically, TVM used to relies on LinkOnceAnyLinkage type (which set the global to nullptr) during initialization to cache function handle. We found that the compiled result will crash under this linkage type(possibly due to the value not available, or initializer is not initialized to nullptr).  Change linkage type to private can resolve the issue. But we feel that it might be something that you may want to know and resolve in fastcomp.   Ideally, we want to keep LinkOnceAnyLinkage type so that the final linked program only have one cached functional handle globally per name

See related discussion here by @phisiart  https://github.com/dmlc/nnvm/pull/369 . Unfortunately at the moment we don't have a minimum reproduce example unless we change TVM back to LinkOnceAnyLinkage and rerun @phisiart 's PR, but we are pretty certain it is due to LinkOnceAnyLinkage and hope that information can help to find what is going on in here.

**Comment by kripken** [comment]
Is this compiling fastcomp itself to js, or compiling an output from it?

In both cases, fastcomp doesn't modify any linkage internals from LLVM, so it's possible this is an upstream LLVM bug. But it could also be a bug in compiling to js/wasm.

**Comment by tqchen** [comment]
We are using fastcomp to compile  in memory LLVM IR(which we generate) to js. The LinkOnceAnyLinkage option works fine for other backends we have (like compile to x86) so we assume it might be related to fastcomp

**Comment by kripken** [comment]
Interesting. No guesses as to what could cause a difference in fastcomp, but perhaps one of our optimization passes somehow is influenced by that linkage? If you can create a testcase of LLVM IR showing the problem, that would help.
