### ISSUE TITLE
Add option to disable "emitted code will contain very large numbers of local variables..." warning

### ISSUE THREAD

**Issue by joelvaneenwyk** [emscripten-core/emscripten-fastcomp#219]
In my builds I always strive to get to zero warnings and it seems compilation returns -1 if the above warning is issued meaning the build never can succeed. Would be great to have a way to disable this.

Implementation note: seems this would be fairly easy to add in JSBackend.cpp.

**Comment by kripken** [comment]
Perhaps we can just remove that warning. It was added in the days when JS VMs did very very poorly on such big functions, which is less true today, and especially less true on wasm. An option might be to just disable the warning on wasm.

**Comment by joelvaneenwyk** [comment]
I'm in favor of removing it entirely and not just for wasm -- partially because I'm not using wasm yet, but in general I like the idea of not diverging too much. Alternatively you could make an option to specify the number of local variables before it gives the warning and a value of -1 just means no limit. Not sure how much precedence there is for that convention though.

**Comment by kripken** [comment]
Yeah, I think we can just remove it. Opened #220
