### ISSUE TITLE
Could not verify LLVM version: [Error 2] No such fil or directory

### ISSUE THREAD

**Issue by Praveer1981** [emscripten-core/emscripten-fastcomp#246]
Hi,
I have upgraded and activated the latest version of Emscripten[1.38.21] on the virtual linux machine.

upon doing` $source ./emsdk_env.sh`

I got below output.
```
Adding directories to PATH:
PATH += /home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21
PATH += /home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21/clang/e1.38.21_64bit
PATH += /home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21/node/8.9.1_64bit/bin
PATH += /home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21/emscripten/1.38.21

Setting environment variables:
EMSDK = /home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21
EM_CONFIG = /home/praveer/.emscripten
BINARYEN_ROOT = /home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21/clang/e1.38.21_64bit/binaryen
EMSCRIPTEN = /home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21/emscripten/1.38.21
```
next I ran below command
praveer@praveer-Virtual-Machine:~/Praveer_ICUSource$ echo $EMSCRIPTEN
/home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21/emscripten/1.38.21

$emcc
and here are the errors:
```
shared:CRITICAL: Could not verify LLVM version: [Errno 2] No such file or directory
root:INFO: Checking JS engine ['/home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21/node/8.9.1_64bit/bin/node'] failed. Check your config file. Details: Expected the command ['/home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21/node/8.9.1_64bit/bin/node', '/home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21/emscripten/1.38.21/src/hello_world.js'] to finish with return code 0, but it returned with code 255 instead! Output: 
root:CRITICAL: The JavaScript shell (['/home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21/node/8.9.1_64bit/bin/node']) does not seem to work, check the paths in the config file
```

Is there anyone who can help me on this

**Comment by sbc100** [comment]
Is this actually a linux VM?  If it is then it won't be able to run binaries from the windows emsdk.  You will want to run `./emsdk install latest` from within the linux VM to get the linux SDK.  I would not advice sharing the emsdk directory between windows and the linux VM (assuming that is what you are doing).

What happens when you try to run `/home/praveer/PraveerEmscripten/rtfactory/emsdk_win.1.38.21/node/8.9.1_64bit/bin/node`?

**Comment by Praveer1981** [comment]
Dear Sam Clegg,
Yes, You are right. It's actually a Linux VM. I managed to get rid of this
issue. Actually, I was trying to run binaries which were built on the
windows machine. To me, the error thrown was not clear, perhaps, misleading.
Later, I build binaries on the linux machine and able to run the command.

I am sorry to post this message :(
Thanks a lot for your response.
Kind Regards,
Praveer
