### ISSUE TITLE
Reduce size of fastcomp repository

### ISSUE THREAD

**Issue by Yzrsah** [emscripten-core/emscripten-fastcomp#247]
The 350 MB clone can cause some issues with integration of fastcomp.

```
Receiving objects: 100% (1475212/1475212), 344.05 MiB
```

What efforts could be taken to reduce the size of the repository?

**Comment by kripken** [comment]
This is a fork of LLVM, and LLVM is just large and has a long history, so the size is unavoidable. Why does the size concern you, though? Most users should get a binary build (through the emsdk), so the size of the source repo doesn't affect them in any way.

**Comment by Zyrsha** [comment]
Building dev forks, and also having developers do a recursive clone of project.
It can be an issue when multiple libraries are combined together.
Multiply size of Fastcomp with 20 other similarly sizes libraries, and we have 5 GB of deps to download.

**Comment by sbc100** [comment]
If you are am emscripten user, as @kripken says you shouldn't need to clone this repo at all, you use pre-built binaries. 

If you are a developer who wants to build their own fastcomp without downloading so much you could try a shallow clone with `--depth=1`.

I'm not sure what you mean by "recusive clone".  fastcomp is not a direct dependency of emscripten.  Its not listed in .gitmodule for example.  Rather it is an optional repo that developers can clone if they choose to build fastcomp from source.

I'm not sure what project you are talking about that has 20 fastcomp-sized dependencies.  emscripten certainly doesn't.
