### ISSUE TITLE
Error: Undefined symbol

### ISSUE THREAD

**Issue by FarooqAR** [emscripten-core/emscripten-fastcomp#253]
I get this error when I try to compile my C++ project with emscripten. I am able to compile it without any issue with native compiler. The command I ran is:

```shell
emcc main.cpp -s USE_SDL=2 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s USE_SDL_IMAGE=2 -s USE_SDL_MIXER=2 -s WASM=1 -s DEMANGLE_SUPPORT=1 -s SDL2_IMAGE_FORMATS='["png"]' -o dist/index.html --preload-file assets
``` 

```
error: undefined symbol: _ZN4Game11GetInstanceEv
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: _ZN4Game12HandleEventsEv
error: undefined symbol: _ZN4Game4InitEPKciiiib
error: undefined symbol: _ZN4Game6RenderEv
error: undefined symbol: _ZN4Game6UpdateEv
Error: Aborting compilation due to previous errors
shared:ERROR: '<root>/emsdk/emsdk/node/8.9.1_64bit/bin/node <root>/emsdk/emsdk/emscripten/tag-1.38.22/src/compiler.js /tmp/tmpxsrpuqwp.txt <root>/emsdk/emsdk/emscripten/tag-1.38.22/src/library_pthread_stub.js' failed (1)
```
The compilation completes without errors with the flag `ERROR_ON_UNDEFINED_SYMBOLS=0` but then I get this error in the console when I open `index.html` in the browser:
```
> wasm streaming compile failed: TypeError: Response has unsupported MIME type
> falling back to ArrayBuffer instantiation
> missing function: _ZN4Game11GetInstanceEv
> warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling
```
* After a bit of googling, it seems to be a name mangling error 
* These functions (methods of the `Game` class) are not overloaded
* It might be similar to [this](https://github.com/emscripten-core/emscripten/issues/7393)

**Comment by sbc100** [comment]
Where is "Game::GetInstance()" defined in your project?  I only see
main.cpp on the command line.  Is there a game library you need to add to
the link line?

**Comment by FarooqAR** [comment]
I assume it resolves all the headers recursively from the `main.cpp`, no?
