### ISSUE TITLE
Error building project with llvm_root using fastcomp

### ISSUE THREAD

**Issue by laura-ft** [emscripten-core/emscripten-fastcomp#254]
When I try to execute a c file with emcc having set LLVM_ROOT to fastcomp/build/bin i get the following errors:

> emscripten:INFO: generating system asset: is_vanilla.txt... (this will be cached in "/home/laura/.emscripten_cache/is_vanilla.txt" for subsequent builds)
> emscripten:INFO:  - ok
> emscripten:INFO: generating system library: libdlmalloc.bc... (this will be cached in "/home/laura/.emscripten_cache/asmjs/libdlmalloc.bc" for subsequent builds)
> emscripten:INFO:  - ok
> emscripten:INFO: generating system library: libpthreads_stub.bc... (this will be cached in "/home/laura/.emscripten_cache/asmjs/libpthreads_stub.bc" for subsequent builds)
> emscripten:INFO:  - ok
> emscripten:INFO: generating system library: libc.bc... (this will be cached in "/home/laura/.emscripten_cache/asmjs/libc.bc" for subsequent builds)
> emscripten:INFO:  - ok
> emscripten:INFO: generating system library: libcompiler_rt.a... (this will be cached in "/home/laura/.emscripten_cache/asmjs/libcompiler_rt.a" for subsequent builds)
> emscripten:INFO:  - ok
> emscripten:INFO: generating system library: libc-wasm.bc... (this will be cached in "/home/laura/.emscripten_cache/asmjs/libc-wasm.bc" for subsequent builds)
> emscripten:INFO:  - ok
> emscripten:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/home/laura/.emscripten_cache/asmjs/generated_struct_info.json" for subsequent builds)
> Traceback (most recent call last):
>   File "/home/laura/emsdk/emscripten/1.38.28/emcc.py", line 3220, in <module>
>     sys.exit(run(sys.argv))
>   File "/home/laura/emsdk/emscripten/1.38.28/emcc.py", line 1882, in run
>     final = shared.Building.emscripten(final, target + '.mem', js_libraries)
>   File "/home/laura/emsdk/emscripten/1.38.28/tools/shared.py", line 2315, in emscripten
>     emscripten.run(infile, outfile, memfile, js_libraries)
>   File "/home/laura/emsdk/emscripten/1.38.28/emscripten.py", line 2493, in run
>     shared.Settings.STRUCT_INFO = shared.Cache.get(generated_struct_info_name, ensure_struct_info, extension='json')
>   File "/home/laura/emsdk/emscripten/1.38.28/tools/cache.py", line 123, in get
>     temp = creator()
>   File "/home/laura/emsdk/emscripten/1.38.28/emscripten.py", line 2490, in ensure_struct_info
>     gen_struct_info.main(['-qo', out, path_from_root('src', 'struct_info.json')])
>   File "/home/laura/emsdk/emscripten/1.38.28/tools/gen_struct_info.py", line 532, in main
>     struct_info = inspect_code(header_files, cpp_opts, structs, defines)
>   File "/home/laura/emsdk/emscripten/1.38.28/tools/gen_struct_info.py", line 423, in inspect_code
>     return parse_c_output(info)
>   File "/home/laura/emsdk/emscripten/1.38.28/tools/gen_struct_info.py", line 287, in parse_c_output
>     if line[0] == 'K':
> IndexError: string index out of range

I have the emscripten and fastcomp versions 1.38.28 .

Thank you in advance.

**Comment by kripken** [comment]
Not sure what went wrong here. Perhaps building with `EMCC_DEBUG=1` in the environment would show something useful in the debug logging.
