### ISSUE TITLE
Undefined Symbol : Qt wasm build

### ISSUE THREAD

**Issue by izzaNaqvi2** [emscripten-core/emscripten-fastcomp#257]
INFO:root: - ok
emcc: warning: cannot represent a NaN literal '0xdb9e3d0' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   ret double 0x7FF4000000000000 in _ZL7qt_snanv.10473()
error: undefined symbol: _ZN10QQuickItem10classBeginEv
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: _ZN10QQuickItem10itemChangeENS_10ItemChangeERKNS_14ItemChangeDataE
error: undefined symbol: _ZN10QQuickItem10touchEventEP11QTouchEvent
error: undefined symbol: _ZN10QQuickItem10wheelEventEP11QWheelEvent
error: undefined symbol: _ZN10QQuickItem11qt_metacallEN11QMetaObject4CallEiPPv
error: undefined symbol: _ZN10QQuickItem11qt_metacastEPKc
error: undefined symbol: _ZN10QQuickItem12focusInEventEP11QFocusEvent
error: undefined symbol: _ZN10QQuickItem12updatePolishEv
error: undefined symbol: _ZN10QQuickItem13dragMoveEventEP14QDragMoveEvent
error: undefined symbol: _ZN10QQuickItem13focusOutEventEP11QFocusEvent
error: undefined symbol: _ZN10QQuickItem13keyPressEventEP9QKeyEvent
error: undefined symbol: _ZN10QQuickItem14dragEnterEventEP15QDragEnterEvent
error: undefined symbol: _ZN10QQuickItem14dragLeaveEventEP15QDragLeaveEvent
error: undefined symbol: _ZN10QQuickItem14hoverMoveEventEP11QHoverEvent
error: undefined symbol: _ZN10QQuickItem14mouseMoveEventEP11QMouseEvent
error: undefined symbol: _ZN10QQuickItem15geometryChangedERK6QRectFS2_
error: undefined symbol: _ZN10QQuickItem15hoverEnterEventEP11QHoverEvent
error: undefined symbol: _ZN10QQuickItem15hoverLeaveEventEP11QHoverEvent
error: undefined symbol: _ZN10QQuickItem15keyReleaseEventEP9QKeyEvent
error: undefined symbol: _ZN10QQuickItem15mousePressEventEP11QMouseEvent
error: undefined symbol: _ZN10QQuickItem16mouseUngrabEventEv
error: undefined symbol: _ZN10QQuickItem16releaseResourcesEv
error: undefined symbol: _ZN10QQuickItem16touchUngrabEventEv
error: undefined symbol: _ZN10QQuickItem17componentCompleteEv
error: undefined symbol: _ZN10QQuickItem17mouseReleaseEventEP11QMouseEvent
error: undefined symbol: _ZN10QQuickItem21childMouseEventFilterEPS_P6QEvent
error: undefined symbol: _ZN10QQuickItem21mouseDoubleClickEventEP11QMouseEvent
error: undefined symbol: _ZN10QQuickItem21windowDeactivateEventEv
error: undefined symbol: _ZN10QQuickItem5eventEP6QEvent
error: undefined symbol: _ZN10QQuickItem7setFlagENS_4FlagEb
error: undefined symbol: _ZN10QQuickItem9dropEventEP10QDropEvent
error: undefined symbol: _ZN10QQuickItemC2EPS_
error: undefined symbol: _ZN10QQuickItemD2Ev
error: undefined symbol: _ZN11QQmlPrivate11qmlregisterENS_16RegistrationTypeEPv
error: undefined symbol: _ZN11QQmlPrivate30qdeclarativeelement_destructorEP7QObject
error: undefined symbol: _ZN11QQuickStyle8setStyleERK7QString
error: undefined symbol: _ZN11QSGGeometry14setDrawingModeEj
error: undefined symbol: _ZN11QSGGeometry33defaultAttributes_TexturedPoint2DEv
error: undefined symbol: _ZN11QSGGeometryC1ERKNS_12AttributeSetEiii
error: undefined symbol: _ZN12QApplication4execEv
error: undefined symbol: _ZN12QApplicationC1ERiPPci
error: undefined symbol: _ZN12QApplicationD1Ev
error: undefined symbol: _ZN15QSGGeometryNode11setMaterialEP11QSGMaterial
error: undefined symbol: _ZN16QSGTransformNodeC2Ev
error: undefined symbol: _ZN16QSGTransformNodeD2Ev
error: undefined symbol: _ZN20QSGBasicGeometryNode11setGeometryEP11QSGGeometry
error: undefined symbol: _ZN21QQmlApplicationEngine4loadERK4QUrl
error: undefined symbol: _ZN21QQmlApplicationEngineC1EP7QObject
error: undefined symbol: _ZN21QQmlApplicationEngineD1Ev
error: undefined symbol: _ZN24QSGOpaqueTextureMaterial10setTextureEP10QSGTexture
error: undefined symbol: _ZN24QSGOpaqueTextureMaterialC1Ev
error: undefined symbol: _ZN2Qc5Style5Style10initializeER10QQmlEngine
error: undefined symbol: _ZN2Qc5Style5Style11getInstanceEv
error: undefined symbol: _ZN2Qc5Style5Style18selectCurrentThemeE7QString
error: undefined symbol: _ZN7QSGNode15appendChildNodeEPS_
error: undefined symbol: _ZN7QSGNode7setFlagENS_4FlagEb
error: undefined symbol: _ZN7QSGNode8setFlagsE6QFlagsINS_4FlagEEb
error: undefined symbol: _ZNK10QQuickItem12boundingRectEv
error: undefined symbol: _ZNK10QQuickItem15textureProviderEv
error: undefined symbol: _ZNK10QQuickItem17isTextureProviderEv
error: undefined symbol: _ZNK10QQuickItem6windowEv
error: undefined symbol: _ZNK10QQuickItem8clipRectEv
error: undefined symbol: _ZNK10QQuickItem8containsERK7QPointF
error: undefined symbol: _ZNK12QQuickWindow22createTextureFromImageERK6QImage
error: undefined symbol: _ZNK7QSGNode16isSubtreeBlockedEv
error: undefined symbol: _ZThn8_N10QQuickItem10classBeginEv
error: undefined symbol: _ZThn8_N10QQuickItem17componentCompleteEv
error: undefined symbol: _ZN10QQuickItem16staticMetaObjectE
error: undefined symbol: _ZTI10QQuickItem
error: undefined symbol: _ZTI16QSGTransformNode
Error: Aborting compilation due to previous errors
ERROR:root:'/home/izza/emsdk/node/8.9.1_64bit/bin/node /home/izza/emsdk/emscripten/1.38.16/src/compiler.js /tmp/tmpm47Jtu.txt /home/izza/emsdk/emscripten/1.38.16/src/embind/emval.js /home/izza/emsdk/emscripten/1.38.16/src/embind/embind.js /home/izza/emsdk/emscripten/1.38.16/src/embind/emval.js /home/izza/emsdk/emscripten/1.38.16/src/embind/embind.js /home/izza/emsdk/emscripten/1.38.16/src/library_pthread_stub.js' failed (1)
Makefile:229: recipe for target 'designer.js' failed
make: *** [designer.js] Error 1

**Comment by kripken** [comment]
To debug stuff like this, you can use `EMCC_DEBUG=1` in the env to see the commands emcc runs, and `llvm-nm` to see which symbols are present in which input files.
