### ISSUE TITLE
llvm-config: error:  missing libgtest.a

### ISSUE THREAD

**Issue by nscotto** [emscripten-core/emscripten-fastcomp#261]
Hi, 

I am trying to compile TVM modules for webgl, I have installed the TVM web assembly backend following [those instructions](https://github.com/dmlc/tvm/tree/master/web), the problem is that lvm-config is throwing me error of missing libraries in *fastcomp/build_incoming_64/lib*: *libgtest.a* and *libgtest_main.a*, and I cannot find them in any directories.

**Comment by sbc100** [comment]
Its looks like its failing to build fastcomp.  Can you provide the command line that is failing along with the output?

**Comment by nscotto** [comment]
It is when trying to compile TVM library emscripten fastcomp, I modified the file *config.cmake* in *build* folder:

```
# Whether build with LLVM support
# Requires LLVM version >= 4.0
#
# Possible values:
# - ON: enable llvm with cmake's find search
# - OFF: disable llvm
# - /path/to/llvm-config: enable specific LLVM when multiple llvm-dev is available.
#set(USE_LLVM "/usr/lib/llvm-8/bin/llvm-config")
set(USE_LLVM "/opt/emsdk/clang/fastcomp/build_incoming_64/bin/llvm-config")
```
The last line is the one I modified following the TVM web [instructions](https://github.com/dmlc/tvm/tree/master/web). However instructions are not quite clear for me as it says to modify `LLVM_CONFIG`, but as you can see in the comments of the file `USE_LLVM` seems to be the environment that points to `llvm-config`. In order to check, I have also tried leaving `USE_LLVM` to the normal path and adding the `SET(LLVM_CONFIG "/opt/emsdk/clang/fastcomp/build_incoming_64/bin/llvm-config")` without any success as well.

In the first case, it is when runing `cmake ..` from *build* directory (see [tvm install from sources](https://docs.tvm.ai/install/from_source.html)) that I get the error:

```
-- Build with RPC support...
-- Build with Graph runtime support...
-- Build VTA runtime with target: sim
-- Build with OpenCL support
-- Build with OpenGL support
-- Custom Vulkan SDK PATH=/opt/vulkanSdk/1.1.106.0
-- Vulkan_INCLUDE_DIRS=/opt/vulkanSdk/1.1.106.0/include/usr/include/spirv-tools/usr/include/SPIRV/usr/include/SPIRV
-- Vulkan_LIBRARY=/usr/lib/x86_64-linux-gnu/libvulkan.so
-- Vulkan_SPIRV_TOOLS_LIBRARY=/usr/lib/x86_64-linux-gnu/libSPIRV-Tools.a
-- Build with VULKAN support
-- Use llvm-config=/opt/emsdk/clang/fastcomp/build_incoming_64/bin/llvm-config
llvm-config: error: component libraries and shared library

llvm-config: error: missing: /opt/emsdk/clang/fastcomp/build_incoming_64/lib/libgtest.a
llvm-config: error: missing: /opt/emsdk/clang/fastcomp/build_incoming_64/lib/libgtest_main.a
llvm-config: error: component libraries and shared library

llvm-config: error: missing: /opt/emsdk/clang/fastcomp/build_incoming_64/lib/libgtest.a
llvm-config: error: missing: /opt/emsdk/clang/fastcomp/build_incoming_64/lib/libgtest_main.a
-- /opt/emsdk/clang/fastcomp/src/include/opt/emsdk/clang/fastcomp/build_incoming_64/include
CMake Error at cmake/util/FindLLVM.cmake:71 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  cmake/modules/LLVM.cmake:22 (find_llvm)
  CMakeLists.txt:193 (include)


CMake Error at cmake/util/FindLLVM.cmake:72 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  cmake/modules/LLVM.cmake:22 (find_llvm)
  CMakeLists.txt:193 (include)


-- Found LLVM_INCLUDE_DIRS=/opt/emsdk/clang/fastcomp/src/include/opt/emsdk/clang/fastcomp/build_incoming_64/include
-- Found LLVM_DEFINITIONS= -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found TVM_LLVM_VERSION=60
-- Build with LLVM 
-- Set TVM_LLVM_VERSION=60
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Configuring incomplete, errors occurred!
See also "/home/SERILOCAL/n.perto/Documents/tvm/build/CMakeFiles/CMakeOutput.log".
```

In the second case, it compiles but at the end I don't get the asm.js target in tvm so I guess it was not the way to do it.

**Comment by sbc100** [comment]
It looks like `emsdk` by default will build llvm with `-DLLVM_INCLUDE_TESTS=OFF` which I guess means libgtest never gets built.

The first error you are getting from llvm-config you can disable by passing `--link-static` to llvm-config.   I can't see an options to disable the libgtest errors though.

You can pass `--build-tests` to your `emsdk install` command to enable testing your llvm builld. Thats most likely the simplest solution.

**Comment by nscotto** [comment]
Solved the problem!
Thanks a lot.
