### ISSUE TITLE
AssertionError: SIMD is used, but not supported in WASM mode yet

### ISSUE THREAD

**Issue by nscotto** [emscripten-core/emscripten-fastcomp#262]
Hello,

I am trying to compile a [TVM](https://docs.tvm.ai/tutorials/) module using a [simple example](https://github.com/dmlc/tvm/blob/master/tests/web/prepare_test_libs.py) and I get the error that SIMD is used but not supported in WASM.
Basically the example is trying to compile a module to object code and link it with a runtime library using emcc.
I have modified the code to add the option `-s WASM=0` and I still get the error, I think it might be a problem with emscripten, that is why I am asking here.
The sdk in use is 1.38.31, freshly installed.

**Comment by kripken** [comment]
There is a new and working implementation in the LLVM wasm backend, docs in progress here: https://github.com/emscripten-core/emscripten/pull/8582

(The fastcomp (non-LLVM wasm backend) version is no longer supported. It never supported wasm, and the JS support doesn't exist in browsers anyhow.)

**Comment by nscotto** [comment]
Ok, how can I enable it on my installation?

**Comment by kripken** [comment]
We are still working on buildbots for the llvm wasm backend. For now on linux you can use `emsdk install latest-upstream`. Otherwise you can build upstream LLVM+clang (from new master) manually. But bots should be ready pretty soon.

**Comment by nscotto** [comment]
Ok, thanks.

**Comment by nscotto** [comment]
Hi, I am still trying to figure out what can I do in order to bypass this error and use the webgl backend in tvm.
I am not sure how tvm works in conjunction with fastcomp, it needs in order to work and if actual version of tvm is updated to work with latest version of fastcomp, so the problem may come from the tvm framework, but it can also be a simple line of config to change in the building of the modules or tvm library.
So I am sorry to ask for more information here but I am new to those tools and also I did not get any answer on the tvm discussion forum.
Thanks in advance.

**Comment by kripken** [comment]
Using `emsdk install latest-upstream` is now supported on all OSes, so you should be able to use it for testing. We will have an official announcement soon, but it's basically ready right now.

**Comment by nscotto** [comment]
Okay thanks.
I found that the issue was that the option `-s WASM=0` was not passed to the compiler at the right moment in some TVM scripts, so I corrected it and now it's working. That also means the problem  was not coming from fastcomp.
Thank you.
