### ISSUE TITLE
CommandLine Error: Option `help-list` registered more than once!

### ISSUE THREAD

**Issue by nscotto** [emscripten-core/emscripten-fastcomp#263]
Hello,
I am trying to build a [TVM](https://github.com/dmlc/tvm) module with webgl backend, ie, using emscripten's fastcomp, and I amn getting this error message:
```
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
The error seems to come from fastcomp installation (not tvm) as  it's the only place where I can grep `CommandLine` or `help-list` in source files.
I have installed `latest` sdk and `clang-incoming-64bit` with `--build-tests` options.

It seems that the option `help-list` is passed more than once to the command line, I don't know what is causing this issue.
Could you help me figuring this out please?

Thank you

**Comment by sbc100** [comment]
I don't think this is a fastcomp issue otherwise everyone would be seeing.

What command are you running to generate that error?   Are you building a custom compiler that extends or used fastcomp somehow?  I can't see how fastcomp on its own could generate this error.

**Comment by sbc100** [comment]
This error comes from a command line option being linked into the binary twice.  So I guess you are building a custom binary that is not clang?  (Since fastcomp is generally know to work).
