### ISSUE TITLE
Will you make tags in this repo again which are in sync with emscripten?

### ISSUE THREAD

**Issue by svenstaro** [emscripten-core/emscripten-fastcomp#264]
emscripten, emscripten-fastcomp, emscripten-fastcomp-clang used to all carry the same tags at the same time but this is not the case anymore. For instance, what tag of emscripten-fastcomp am I supposed to be using to go along with emscripten 1.38.36? Will you sync the tags up again?

**Comment by kripken** [comment]
I updated those tags now.

Docs for how to figure out the revisions are here: https://github.com/emscripten-core/emscripten/blob/incoming/docs/process.md#minor-version-updates-1xy-to-1xy1

Note that we are going to switch away from fastcomp as our default backend soon, which is why there isn't any development going on there, and I forgot to update the tags. I suppose we can still tag versions there for now. But we encourage people to try to upstream llvm wasm backend at this point (blogpost coming soon with more details!).

**Comment by svenstaro** [comment]
Thanks for the tags. I'd generally be happy to lose the fastcomp part but I'd need instructions on how to use the other backend. Happy to wait for the blog article for that, though. As context: I package emscripten for Arch Linux.

**Comment by kripken** [comment]
It's pretty simple, and should work right now (except for a few features specific to fastcomp). You can get it with `emsdk install latest-upstream` and likewise add `-upstream` for the activate command. Or for building manually (which maybe you're doing as a packager?) you just need to get very recent llvm, and build it (it will build the wasm backend by default, but must also make sure it builds clang and wasm-ld, which I'm not sure are on by default). Then just point emscripten to that llvm build.

**Comment by kripken** [comment]
Oh, and also this requires a very recent emscripten.

Docs on how we tag releases are here. That explains how you can find which emscripten commit goes with which LLVM commit etc. https://github.com/emscripten-core/emscripten/blob/incoming/docs/process.md#minor-version-updates-1xy-to-1xy1

**Comment by svenstaro** [comment]
Thanks for the description but that's still too vague for me. Basically I'd be really happy if you could make a short compile script so that I can see how everything fits together and what gets cloned where.

**Comment by kripken** [comment]
The main thing to compile is LLVM. Here is where the waterfall bots build it: https://github.com/WebAssembly/waterfall/blob/master/src/build.py#L790 The only other thing you need to build is binaryen, which is done here: https://github.com/WebAssembly/waterfall/blob/master/src/build.py#L932

In general though, building them is basically following the upstream project's normal build instructions, links to them are here, https://emscripten.org/docs/building_from_source/index.html

**Comment by svenstaro** [comment]
> Oh, and also this requires a very recent emscripten.
> 
> Docs on how we tag releases are here. That explains how you can find which emscripten commit goes with which LLVM commit etc. https://github.com/emscripten-core/emscripten/blob/incoming/docs/process.md#minor-version-updates-1xy-to-1xy1

I really can't find out how to see which LLVM commit goes into with which emscripten tag. Mind shedding some light on that?

Apart from that, I had to hack `settings_template_readonly.py` a bit to make sure it'll work with my custom LLVM for emscripten. I just took the current master HEAD of LLVM. Hopefully it'll work.

**Comment by kripken** [comment]
@svenstaro I opened a PR now with more docs to answer that question, https://github.com/emscripten-core/emscripten/pull/8829 Is that ok, or is there more I should clarify?

**Comment by svenstaro** [comment]
Seems like a great start! There are some details with installation that I'd like clarified. For instance, which files from LLVM do you actually require? Currently I'm installing lld, clang and clang++ as can be seen in the [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/emscripten).

Does that suffice?

**Comment by kripken** [comment]
I believe a few more are needed: wasm-ld (just a symlink for lld I think?), llvm-nm, etc. I added a commit to that PR now with what I hope is the full list.

**Comment by svenstaro** [comment]
From my view, it's now almost sufficient to provide a good user experience as a maintainer. However, I'm also doing this to make sure the paths are correct for a user to start with so that might be a good thing to suggest to other maintainers as well:

    sed -i 's|EMSCRIPTEN_ROOT.*|EMSCRIPTEN_ROOT = "/usr/lib/emscripten"|g' tools/settings_template_readonly.py
    sed -i 's|LLVM_ROOT.*|LLVM_ROOT = "/usr/lib/emscripten-llvm"|g' tools/settings_template_readonly.py

**Comment by svenstaro** [comment]
By the way, it seems that those binaries are not sufficient. Could you check that out in depth and write down the entire list of binaries required?

**Comment by kripken** [comment]
@svenstaro Thanks, I updated that PR now with `llc` which was indeed missing, sorry about that (did you see anything else? if you can't tell exactly what's missing, the command that failed for you might help). I also added docs for the `.emscripten` file for packagers, let me know what you think.

**Comment by svenstaro** [comment]
At least `llvm-link` and `opt` are also missing.

**Comment by kripken** [comment]
Oh, those are needed for fastcomp - the docs I wrote were for the wasm backend. I added docs for fastcomp now, thanks.

**Comment by svenstaro** [comment]
My non-fastcomp `emcc` complained about those binaries missing so I don't know. :P

**Comment by kripken** [comment]
Thanks @svenstaro, I forgot about the sanity warnings - those were wrong. Fix in #8853.

**Comment by Beuc** [comment]
Hi. I'm still using fastcomp because I'm relying on emterpreter (I know about the new experimental async but I can't start investigating it right now), so when I'm compiling the latest fastcomp it would help to have up-to-date tags (current 1.38.37 vs. 1.38.41). Would that be possible?

**Comment by kripken** [comment]
Sure, I pushed 1.38.39+ now.

Sorry for forgetting - there is literally no code landing there, so all the tags are just the same...

**Comment by svenstaro** [comment]
Maybe just out the tagging into a release script of yours especially since
it's trivial.

**Comment by Beuc** [comment]
A bit of rationale: I have a compilation script that ensures that all the tags match, which broke, so I had to hard-code 1.38.37 in a couple places; plus when I saw tags missing I had to spent time checking if the reference repository changed or was already deprecated (which was not the case as it's still emsdk's default). So tags are still useful :)

**Comment by kripken** [comment]
@svenstaro - We probably should, yeah. In practice there isn't a script to tag, just a few manual steps that I do each time, so this isn't an automated process.

@Beuc - Yeah, makes sense, I'll make sure to make tags. I just tagged 1.38.42 and updated all repos with them.

**Comment by svenstaro** [comment]
When will fastcomp be entirely deprecated? The problem will then go away by itself. :P

**Comment by kripken** [comment]
@svenstaro yes, that's the goal :)

No specific date yet for removing fastcomp. First we want to switch the default to upstream, for which we need to fix [some blockers](https://github.com/emscripten-core/emscripten/projects/1). Then we need to get feedback and start to plan fastcomp's removal.

**Comment by Beuc** [comment]
Hi,

Tag 1.38.45 is missing - my colleague got puzzled when upgrading our build environment and supposed the new version wasn't published yet :)

**Comment by kripken** [comment]
Thanks @Beuc, looks like we forgot that tag, fixed now!
