### ISSUE TITLE
Error message displays when i excute 'wasm-pack build'

### ISSUE THREAD

**Issue by lamei1224** [emscripten-core/emscripten-fastcomp#270]
i dont know how to solve this problem,so i want someone to help me please.
1. I have installed rust version 
2. when i execute 'wasm-pack build' in https://github.com/paritytech/stateless-blockchain on accumulator-client 
3. Error Message displays
![error message](https://user-images.githubusercontent.com/55862430/84583758-02afe800-ae2f-11ea-96fe-69934c75c12e.png)

**Comment by kripken** [comment]
I think this is in the wrong repo?

**Comment by lamei1224** [comment]
> I think this is in the wrong repo?
Do you know how to solve this problem？Do you think I need to reconfigure the environment？ is there a requirement for the rust version？Thank you！

**Comment by kripken** [comment]
This is not a rust repo, and I don't know the answers to those questions, sorry.
