### ISSUE TITLE
emscript 1.39.X can't be built if using libjpeg

### ISSUE THREAD

**Issue by albjeremias** [emscripten-core/emscripten-fastcomp#271]
```
   ports.fetch_project('libjpeg', 'https://dl.bintray.com/homebrew/mirror/jpeg-9c.tar.gz', 'jpeg-9c', sha512hash=HASH)
urllib2.HTTPError: HTTP Error 403: Forbidden
```
which is described as problem with that domain was taken down... and u need to upgrade emscript?!
here is the upstream issue
emscripten-core/emscripten#14760

so I modified the project flags to be able to use emscript-latest instead of 1.39.X
as seen in here: 
https://github.com/webarkit/jsartoolkit5/pull/15

But i didn't build with fastcomp, which made the code to run really sloppy and to break.

So I realized that probably the problem is that im not using **fastcomp**

And then I tried to fetch emscript-fastcomp-latest.. and puff.. its gone. 
`the fastcomp backend is not getting new builds or releases. Please use the upstream llvm backend or use an older version than 2.0.0 (such as 1.40.1)`

So is there a guide or help on how-to migrate from emscript-fastcmp to llvm ?! where can I start from?!

**Comment by sbc100** [comment]
fastcomp was removed with the 2.0.0 and upstream llvm has replaced it.     In almost all cases upstream llvm should outperform the old fastcomp compiler.

It sounds like you were able to make the switch without any issues, but you noticed some issues with the build.  Can you detail what you mean by "made the code to run really sloppy and to break"?  It sounds like you will need to deal with whatever issues you found there.

**Comment by sbc100** [comment]
Can you open specific issues in the main emscripten repo and we can try to help you there?

This repo is not active anymore.

**Comment by albjeremias** [comment]
ok. thank you. no problem
