### ISSUE TITLE
Disable OCaml bindings if ctypes >=0.3 is not found

### ISSUE THREAD

**Issue by gagern** [emscripten-core/emscripten-fastcomp#85]
Switching from master to incoming, my emsdk fails to build fastcomp:

```
-- Found OCaml: /usr/bin/ocamlfind  
-- OCaml bindings enabled.
CMake Error at cmake/modules/FindOCaml.cmake:76 (message):
  ocamlfind: Package `ctypes' not found
Call Stack (most recent call first):
  cmake/config-ix.cmake:533 (find_ocamlfind_package)
  CMakeLists.txt:347 (include)
```

Please either disable OCaml manually or import llvm-mirror/llvm@0245b12df2c1c0604d98e8f398f99a37bf34f978 aka SVN r223195, first released in llvm [release_36](https://github.com/llvm-mirror/llvm/tree/release_36).

**Comment by kripken** [comment]
We hope to merge LLVM 3.6 soon, so I think it's best to wait on that and not cherry-pick that commit.

**Comment by juj** [comment]
Hmm, looks like even after the LLVM 3.6 merge, we don't have that bugfix present (https://github.com/kripken/emscripten-fastcomp/blob/incoming/cmake/config-ix.cmake#L532), so perhaps there's some other commits that we are missing?

**Comment by kripken** [comment]
We didn't merge 3.6 release, but the current state of 3.6 trunk that PNaCl was on. When PNaCl merges to LLVM trunk, we will merge them and get this.
